[cerebrium.deployment]
name = "min"                       # or whatever your app is called
python_version = "3.12"
disable_auth = true
include = ["./*", "main.py", "cerebrium.toml"]
exclude = [".*"]

[cerebrium.runtime.custom]
entrypoint = ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
port = 8080
healthcheck_endpoint = "/health"
readycheck_endpoint = "/health"

[cerebrium.dependencies.pip]
fastapi = "latest"
uvicorn = "latest"
httpx = "latest"
websockets = "latest"
jupyterlab = "latest"
