[cerebrium.deployment]
name = "min"                # <-- your app name (appears in the URL)
disable_auth = true
include = ["./*"]
exclude = [".*"]

[cerebrium.runtime.custom]
port = 8192
dockerfile_path = "./Dockerfile"
healthcheck_endpoint = "/health"
readycheck_endpoint = "/health"

[cerebrium.hardware]
cpu = 2
memory = 4.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 1
max_replicas = 1
replica_concurrency = 1
cooldown = 3600
